### ISSUE TITLE
A4 page

### ISSUE THREAD

**Issue by SaskoJA** [kendallb/PrintHtml#3]
Hello, please can you build version with paper size set to A4?

**Comment by kendallb** [comment]
Ahh, I see I have it hard coded to US letter. Probably should add this as a command line option to b able to change the paper type that is used. At the moment I don't have the Qt tools installed to build this as I have rebuild my Windows VM since I write this. So I will need to install the tools again and then make some changes.

**Comment by kendallb** [comment]
Ok try the new version in the deploy directory. I added a new -a parameter to select between A4 and Letter paper.

**Comment by SaskoJA** [comment]
Many thanks. This is it! You made my day.

It is possible build with higher QT version? This version QT have incorrect letter spacing under Windows OS.
[https://bugreports.qt.io/browse/QTBUG-28774](https://bugreports.qt.io/browse/QTBUG-28774)

**Comment by kendallb** [comment]
Unfortunately it is not possible because they dropped the QtWebKit control in Qt after version 5.0 for some reason. There was talk of bringing it back but last I checked it has not happened. I did see some third party libraries to bring it back but last time I tried I could not get it working. It would be nice to have if build with something later than 4.8.6.
