### ISSUE TITLE
Only base64 png picture

### ISSUE THREAD

**Issue by SaskoJA** [kendallb/PrintHtml#5]
Hello, is there any possible way print some other picture formats than base64 png? Javascript doesnt work too. ts there any way to get it work?

**Comment by kendallb** [comment]
Printing of images works fine for me as we already use that? We print both PNG and JPG files when loading a page from the internet. Perhaps you have an example of a page that is not working?

As for Javascript, I am not sure that will ever work as I don't think Javascript runs even if you print in a browser?

**Comment by SaskoJA** [comment]
Im not able print any jpg picture, it doesnt matter if its on Internet or local. Example: [http://update.8u.cz/sample.pdf](http://update.8u.cz/sample.pdf)
Yes, Javascript work in browsers when printing (e.g. generating QR codes). In this case Javascript work very strange, some do, some doesnt. 
Another one question, it is possible control orientation of printed document (Portrait/Landscape)?

**Comment by Nineapsofttech** [comment]
I think the best way to use or to print something you need to render every with html code so the library can handle it with http status code .
Sometimes if your server response the image too slow you would see the white space instead of images.
so if it possible I suggest to use base64 image data as I uses it in my production for long time it work great and never have any problem

**Comment by khalidchawtany** [comment]
>Another one question, it is possible control orientation of printed document (Portrait/Landscape)?

@SaskoJA now it is possible to specify orientation using -o flag.
